### ISSUE TITLE
Persistence not working with `docker-compose --profile postgres up`

### ISSUE THREAD

**Issue by arkanoid87** [camunda-community-hub/zeeqs#357]
Restarting the provided docker compose stack (1 broker, 1 partition) without destroying the volumes won't persist the data

1) `docker-compose --profile postgres up`
2) Use `DeployProcess` gRPC to deploy BPMN file
3) run query in `graphiql`
```
{
  processes {
    totalCount
  }
}
```
result:
```
{
  "data": {
    "processes": {
      "totalCount": 1
    }
  }
}
```
check pgsql table `process`: 1 row
4) SIGINT docker compose stack
5) `docker compose --profile postgres down` (remove containers and network, preserve volumes)
6) `docker-compose --profile postgres up` restore stack with existing volume in place

docker log shows postgres volume is found
```docker
zeeqs-postgres-zeeqs-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
```
7) run query in `graphiql`
```
{
  processes {
    totalCount
  }
}
```
result:
```
{
  "data": {
    "processes": {
      "totalCount": 0
    }
  }
}
```
check pgsql table `process`: 0 row

**Comment by rcolombodesouza** [comment]
I have a similar issue.
I have a module which deploy a bunch of processes to Zeebe, which I will call it X. I make use of ZeeQS to retrieve information on how many instances of a process are currently active.

I start the modules in the following order: Zeebe / ZeeQS / X. For a clean start, everything looks ok. For examplification, I deploy 10 processes.
Then I stop Zeebe / ZeeQS / X. I start them again, following the same order and run the 

`{
  processes {
    totalCount
  }
}`

and I got 0 as a result instead of 10.
`{
  "data": {
    "processes": {
      "totalCount": 0
    }
  }
}`

For some reason, if I start ZeeQS before the other two modules, I don`t get this issue.

**Comment by rcolombodesouza** [comment]
I did another test using postgresql. I start Zeebe / ZeeQS / X. I check the PostgreSQL database and all tables which should be filled are filled.
Later, I stop Zeebe / ZeeQS / X and start again. I check the tables again and noticed that the process table is empty, while the other tables are filled.
It might be a bug when filling up the process table.
Note that this issue does not happen aways and sometimes I have to perform many stop/starts.

**Comment by saig0** [comment]
@arkanoid87 & @rcolombodesouza thank you for reporting and analyzing. :+1: It is really valuable. 

I will have a look in the next two weeks. Currently, I'm too busy.

**Comment by rcolombodesouza** [comment]
I tried to debug a bit the zeeqs code and it seems that when the problem happens, the listener from the Process, which is in the HazelcastImporter.kt does not get triggered. Maybe it helps.

**Comment by saig0** [comment]
I found the issue in the configuration. The JPA Hibernate property `ddl-auto` was set to `create`. As a result, the application dropped all database tables on start-up. The fix is to change the property to `update`. 

I'm changing the property in the default config and in the docker-compose. :rocket:
